### PR TITLE
Fix rounding errors (issue #3)

### PR DESCRIPTION
**Pull request by DeeLindesay**
This corrects the problem with recursive rounding by rounding one place at a time, starting from the smallest value place.

As before it is based of rounding to the nearest with the mid-case  (0.5) rounding away from zero.

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
Have you considered what happens when you round 0.249 to one decimal place?  I think with your code it will become 0.25 then 0.3 which is incorrect.

**Comment by DeeLindesay** [comment]
You are of course right.  Code does what I intended, but I'm clearly cracking up.
Will rethink!

**Comment by ForbesLindesay** [comment]
I think it's already very nearly here, you just need to handle the special case of it overflowing (perhaps check for when the length increases?

**Comment by DeeLindesay** [comment]
Was alreading checking for overflow, but have now started rounding from the right place and removed iteration.
Both my new test (which failed originally) and your suggested test, above, (which failed with my original code) now run successfully

**Comment by ForbesLindesay** [comment]
Should we also be handling the case of rounding to 0 decimal places?

**Comment by DeeLindesay** [comment]
We already are. And the tests pass, including the one I added for 519.6 which correctly rounds to 520

**Comment by DeeLindesay** [comment]
FYI. Possible issue crossed my mind.
If system rounded to display on first entry but then sent database the unrounded number, then (depending on dB field size) the database would round according to its own rules.  The data stored would not necessarily match that initially displayed.

Have checked this on 'mySQL' (entering values with 3dp into a numeric(18,2) field and all is well :)
Different databases could operate different rounding rules so could need to consider this elsewhere.

Test results were
```
 Entered	Rounded
 118.233     118.23
 118.235     118.24
 118.237     118.24
 118.243     118.24
 118.245     118.25
 118.247     118.25
-118.233	-118.23
-118.235	-118.24
-118.237	-118.24
-118.243	-118.24
-118.245	-118.25
-118.247	-118.25
 118.996     119.00
```

**Comment by ForbesLindesay** [comment]
Merged in 8a634858ce24b77f0ab4d48198c38c7612a7ecdc

**Pull request closed without merging**
